### ISSUE TITLE
Unable to refence Flora.CssParser in fsx

### ISSUE THREAD

**Issue by nojaf** [Fable-Fauna/Fable.Flora#9]
Hey, I was giving Flora a spin because well this just looks amazing!
However, the following code leads to `No constructors are available for type 'Flora.Stylesheet'`

```fsharp
let Tailwind = Flora.Stylesheet<"C:\\Temp\\fable-react-lazy-suspense\\public\\styles.css">
```

How can I know if the problem is related to my css file? Are there any log files I can check?

**Comment by musheddev** [comment]
The `let` needs to be a `type`.

**Comment by nojaf** [comment]
Wauw yeah obviously, silly me 🙃
Now I get:
![image](https://user-images.githubusercontent.com/2621499/59685404-5ec03c00-91dc-11e9-83aa-84a7991f2805.png)

I'm trying to call this from an `.fsx` script. Repo at [tailwind branch](https://github.com/nojaf/fable-react-lazy-suspense/tree/tailwind). It would be nice to know what is going wrong here.

**Comment by musheddev** [comment]
I'll look into it. One issue about type providers is they get executed by visual studio and F# compiler. Thus referencing their dependencies can get tricky. Which may be why it doesn't work in the script.

**Comment by musheddev** [comment]
Quick Fix: you can copy FSharp.Core and Flora.CssParser into the Flora.CssProvider lib `C:\Users\Orlando\.nuget\packages\flora.cssprovider\0.6.0\lib\netstandard2.0` like so (or where ever paket places them). 

After reading and looking around at other type providers I need to repackage the nuget to include them. Expect a 0.6.1 in the next few days to fix that.

**Comment by nojaf** [comment]
Copying those dlls does make the error go away. It doesn't really handle my css file well. I barely get IntelliSense probably due to the file size though.

**Comment by musheddev** [comment]
Yeah, I noticed it. It is an Ionide issue though, after an initial two second parse time it is snippy in VS. I haven't tried with Ionide 4 yet.

**Comment by musheddev** [comment]
Pushed 0.6.1 with the added assemblies.

**Comment by nojaf** [comment]
0.6.1 fixed the problem. I still don't get any proper intelliSense with my custom tailwind file.
It fails in Rider, super slow in Ionide (but eventually works) and I get an error in VS 17.
![image](https://user-images.githubusercontent.com/2621499/59825768-36982080-9335-11e9-9f64-ebc90dc604f9.png)

**Comment by musheddev** [comment]
I suppose that is because I was in VS 2019 with the 4.6 version of the fsharp compiler. I'll look into it, but I don't have a lot of confidence that I can fix this one.

**Comment by musheddev** [comment]
I get about a 1.5 sec intelliSense delay in ionide-experimental and vs2019.

**Comment by nojaf** [comment]
Ok, thanks for the effort.

**Comment by musheddev** [comment]
Good news, I was able to speed things up dramatically with a concurrent cache in the type provider.
